name: CalendarEvents
author: Nikl
main: me.nikl.calendarevents.Main
version: 1.2.1
website: nikl.me

commands:
  calendarevents:
    description: main command
    usage: /calendarevents
    aliases: [ce]

permissions:
  calendarevents.reload:
    description: Gives permission to use the reload command
    default: op