# ----------------------------------------------------------------------------#
#                                                                             #
#                          Calender Events config                             #
#                                                                             #
# ----------------------------------------------------------------------------#

# the following events are examples for you to understand how to add custom events with this plugin.
# They all get registered and called.
# You can remove or add any event you want, but make sure that the labels (keys) are different.
# To let the plugin do something on these events, go to the section 'listener'.
# For more complex action on events, use the API.
# Please visit www.spigotmc.org/resources/35536/ for more information on the API.
events:
  # Event called on the first of every month
  newMonth:
    timing:
      # This will get called on every first of the month.
      # A date with just two numbers is interpreted as any such day in any month.
      # You can add more dates to the '01' just put a ',' in between (e.g. "01,05,25")
      occasion: "01"
      # 24h format! Event gets called in the first second of the given minute.
      # Each day goes from 00:00 to 23:59 ;)
      time: "00:00"

  # Event called on the first of every week
  newWeek:
    timing:
      occasion: "monday"
      time: "00:00"

  # Event called on the first and second of every year
  newYearAndSecond:
    timing:
      # A date without a year gets called every year
      occasion: "01.01, 02.01"
      time: "00:00"

  # Event called every day, every two hours
  exampleEvent1:
    timing:
      # 'every day' gets translated to 'monday, tuesday, wednesday, thursday, friday, saturday, sunday'
      occasion: "every day"
      time: "01:00,03:00,05:00,07:00,09:00,11:00,13:00,15:00,17:00,19:00,21:00,23:00"

  # Event called every working/school day, every two hours
  workingDays:
    timing:
      occasion: "monday, tuesday, wednesday, thursday, friday"
      time: "01:00,03:00,05:00,07:00,09:00,11:00,13:00,15:00,17:00,19:00,21:00,23:00"

  # Event fired on christmas 2022
  christmas2022:
    timing:
      occasion: "24.12.2022"
      time: "12:00"

# General Calendar Events settings
settings:
  # If your server is in a different timezone then most of your players, you can add hours to the server time here.
  # Example:
  #     Server:   UTC +0
  #     Players:  UTC +1
  #     configure addHoursToServerTime = 1
  #     The events above will trigger at the configured times for your UTC +1 players!
  addHoursToServerTime: 0

# You can listen to calendar events in other plugins.
# But you can also use the listener in this plugin for basic actions.
# For example: send commands, messages, broadcasts, titles
# use & for colors
# %time% will be replaced with the events time (24h format hh:mm)
listener:
  workingDays:
    # %allOnline%    --->  this gets called for every online player and will be replaced with the player name
    commands:
    # - "tell %allOnline% &4Hey there %allOnline% &1:)"

    broadcast: "[Server] &1Hello everyone! Enjoy the game :)"

    broadcastWithPerm:
      perm: "example.perm"
      broadcast: "Hey man, you got a special permission!"

    # %player% will be replaced with the players name
    actionbar:
      # Permission is optional. If empty, the actionbar will be send to everyone
      perm: "example.perm"
      bar: "&1That's a cool actionbar, %player% &r(btw: it's %time%)"

    # %player% will be replaced with the players name
    title:
      # perm is optional. If empty, the title will be send to everyone
      perm: "example.perm"
      title: "&1Hi there %player%"
      subTitle: "It's now &4%time%&r!"

  newYearAndSecond:
    broadcast: "Happy new year!!   Or wait... is it already the 2nd?"

# CalendarEvents is on bStats: https://bstats.org/plugin/bukkit/CalendarEvents
# If you don't want any anonymous data to be send, you can opt it out here.
bstats:
  # Please consider leaving this enabled.
  # Having statistics helps me to see in which projects I should invest more time.
  disabled: false